// This file was auto-generated by ML.NET Model Builder.

using Serilog;

namespace HandwritingRecognitionML.ConsoleApp
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
               .WriteTo.Console()
               .WriteTo.Seq("http://localhost:5341")
               .CreateLogger();

            ModelBuilder.CreateModel();

            Log.Information("=============== End of process ===============");
        }
    }
}